apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: studio-worker-role
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: studio-workers
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["create", "get", "list", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: studio-worker-binding
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: studio-workers
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: studio-worker-role
  apiGroup: rbac.authorization.k8s.io
